### ISSUE TITLE
SnapCraft support

### ISSUE THREAD

**Issue by kerner1000** [fvarrui/JavaPackager#229]
I'm submitting a…

- [ ] bug report
- [X] feature request
- [ ] other

**Short description of the issue/suggestion:**

It would be nice to have support to build a [SnapCraft snap](https://snapcraft.io/docs/java-applications).

**Comment by fvarrui** [comment]
Currently researching about SnapsCraft

**Comment by fvarrui** [comment]
**Snap** package manually built with success for a [sample project](https://github.com/fvarrui/HelloWorldMaven) using next config file (**target/snap/snapcraft.yaml**):

```yaml
name: helloworldmaven
base: core22
version: '1.0.0'
summary: Hello world app packaged with JavaPackager
description: |
  This is HelloWorld description.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  HelloWorldMaven:
    command: HelloWorldMaven
    extensions: [ gnome ]
    environment:
      JAVA_HOME: $SNAP/jre
      PATH: $JAVA_HOME/jre/bin:$PATH

parts:
  app:
    plugin: dump
    source: ./HelloWorldMaven
    source-type: local
```
